<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.Core.TestBase" />
    <PackageReference Include="LagoVista.AspNetCore.Identity" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LagoVista.Campaigns.Repos\LagoVista.Campaigns.Repos.csproj" />
  </ItemGroup>
</Project>
